version: '3.0'
services:
  haste-server:
    build: .
    environment:
      - STORAGE_TYPE=memcached
      - STORAGE_HOST=memcached
      - STORAGE_PORT=11211
      - STATIC_MAX_AGE=311040000
      - STORAGE_EXPIRE_SECONDS=311040000
    ports:
      - 8012:7777
  memcached:
    image: memcached:latest
